---
# file: /roles/aws/tasks/main.yml

- name: Install Python
  sudo: yes
  apt: name=python update_cache=yes
  
- name: Install Python PIP
  sudo: yes
  apt: name=python-pip
  
- name: Install AWS CLI
  sudo: yes
  pip: name=awscli

- name: Install Sysstat
  sudo: yes
  apt: name=sysstat update_cache=yes
